import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {SessionProvider} from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spike Fatbook",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode })=> {
  return (
    <html lang="en">
    <SessionProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      {children}
      </body>
    </SessionProvider>
    </html>
  );
}

export default RootLayout
