# Nome dell'applicazione
spring.application.name=backend

# --- CONFIGURAZIONE DATABASE ---
# La sintassi ${NOME_VARIABILE:valore_default} significa:
# "Usa la variabile d'ambiente se esiste (Docker), altrimenti usa il valore di default (Localhost)"

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/webapp_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:passwordsegreta}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURAZIONE JPA / HIBERNATE ---    
# Dice a Hibernate che stiamo usando Postgres
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Aggiorna automaticamente le tabelle se cambi il codice Java (utile in sviluppo)
spring.jpa.hibernate.ddl-auto=create 

# Mostra le query SQL nel terminale (utile per debug, puoi metterlo a false in futuro)
spring.jpa.show-sql=true

# --- CONFIGURAZIONE SERVER ---
server.port=8080